{'recommendation': [{'name': 'Bibloc/HidroSplit Reversible con ACS HT',
 'gama': None,
 'quantity': None,
 'power': 12.244752,
 'volume': 350.0,
 'order': 1},
 {'name': 'Monobloc + Deposito ACS',
 'gama': None,
 'quantity': None,
 'power': 12.244752,
 'volume': 350.0,
 'order': 2},
 {'name': 'Bibloc/HidroSplit Reversible con ACS',
 'gama': None,
 'quantity': None,
 'power': 12.244752,
 'volume': 350.0,
 'order': 3}],
 'type': 'Vivienda',
 'energy efficiency': True,
 'Control Wifi': False}